name: New CFE workflow notifications
on:
  issues:
    types: [labeled]

permissions:
  issues: write
  contents: write
  pull-requests: write

jobs:
  cfe-created:
    if: github.event.label.name == 'code freeze exception'
    runs-on: ubuntu-20.04
    steps:
      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_RELEASE_SLACK_CHANNEL }}
          slack-text: |
            :arrow_right: New CFE request: ${{ github.event.issue.title }}
            ${{ github.event.issue.html_url }}
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
        continue-on-error: true


  cfe-approved:
    if: github.event.label.name == 'CFE Approved'
    runs-on: ubuntu-20.04
    steps:
      - name: Extract PR info from issue body
        id: extract-pr
        run: |
          BODY="${{ github.event.issue.body }}"

          PR_NUMBER=$(echo "$BODY" | grep -oP 'pull\/\K\d+')

          # Validate input: strictly numeric
          if [[ "$PR_NUMBER" =~ ^[0-9]+$ ]]; then
            echo "Valid PR number: $PR_NUMBER"
            echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          else
            echo "Invalid PR number. Exiting."
            exit 1
          fi

      - name: Add label 'cherry pick to trunk' to PR
        run: |
          OWNER="${{ github.event.repository.owner.login }}"
          REPO="${{ github.event.repository.name }}"
          gh pr edit $PR_NUMBER --add-label "cherry pick to trunk" --repo $OWNER/$REPO
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ env.PR_URL }}

      - name: Extract Release Number from Issue Body
        id: extract-release
        run: |
          BODY="${{ github.event.issue.body }}"

          # Extract the release number using a strict pattern match
          RELEASE_NUMBER=$(echo "$BODY" | grep -oP '\b\d+\.\d+\b')

          # Validate that the release number is in the expected format (X.Y)
          if [[ ! "$RELEASE_NUMBER" =~ ^[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid release number format. Aborting."
            exit 1
          fi

          # Safely output the release number and export it as an environment variable
          echo "RELEASE_NUMBER=$RELEASE_NUMBER" >> $GITHUB_ENV
          echo "Extracted Release Number: $RELEASE_NUMBER"

      - name: Apply Milestone to the Issue
        run: |
          MILESTONE="$RELEASE_NUMBER.0"
          echo "Applying milestone: $MILESTONE"
          gh issue edit ${{ github.event.issue.html_url }} --milestone "$MILESTONE"
        env:
          RELEASE_NUMBER: ${{ env.RELEASE_NUMBER }}
          GH_TOKEN: ${{ github.token }}

      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_CORE_RELESES_DAILY_SLACK_CHANNEL }}
          slack-text: |
            :white_check_mark: CFE request approved: ${{ github.event.issue.title }}
            ${{ github.event.issue.html_url }}
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
        continue-on-error: true

  cfe-rejected:
    if: github.event.label.name == 'CFE Rejected'
    runs-on: ubuntu-20.04
    steps:
      - name: Extract Release Number from Issue Body
        id: extract-release
        run: |
          BODY="${{ github.event.issue.body }}"

          # Extract the release number using a strict pattern match
          RELEASE_NUMBER=$(echo "$BODY" | grep -oP '\b\d+\.\d+\b')

          # Validate that the release number is in the expected format (X.Y)
          if [[ ! "$RELEASE_NUMBER" =~ ^[0-9]+\.[0-9]+$ ]]; then
            echo "Invalid release number format. Aborting."
            exit 1
          fi

          # Safely output the release number and export it as an environment variable
          echo "RELEASE_NUMBER=$RELEASE_NUMBER" >> $GITHUB_ENV
          echo "Extracted Release Number: $RELEASE_NUMBER"

      - name: Apply Milestone to the Issue
        run: |
          MILESTONE="$RELEASE_NUMBER.0"
          echo "Applying milestone: $MILESTONE"
          gh issue edit ${{ github.event.issue.html_url }} --milestone "$MILESTONE"
        env:
          RELEASE_NUMBER: ${{ env.RELEASE_NUMBER }}
          GH_TOKEN: ${{ github.token }}

      - name: Close CFE Issue
        run: gh issue close --comment "Closing issue as CFE is rejected - ${{ github.event.issue.html_url }}" "${{ github.event.issue.html_url }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify Slack
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.CODE_FREEZE_BOT_TOKEN }}
          slack-channel: ${{ secrets.WOO_CORE_RELESES_DAILY_SLACK_CHANNEL }}
          slack-text: |
            :x: CFE request rejected: ${{ github.event.issue.title }}
            ${{ github.event.issue.html_url }}
          slack-optional-unfurl_links: false
          slack-optional-unfurl_media: false
        continue-on-error: true